### ISSUE TITLE
Verify full USFM spec support

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#10]
USFM will be at the top level of the package (no content dir... EVER).

In processing we'll look for a package.json if one exists and we can process it great! if not we'll check if there are a bunch of usfm files and process accordingly. Otherwise we have no idea what to do and should fail.

Add container type `usfm`.

**Comment by neutrinog** [comment]
@jag3773 what do you think about naming the new type `file` or `raw` instead? The type format can then represent any content that is contained in file format instead of in a directory.

Using `usfm` could be problematic because it is technically a format not a type. So if we need to support additional RC that use files we'll need to create more types.

**Comment by jag3773** [comment]
@neutrinog I'd need to see an example of what you are suggesting.  I wouldn't want `file` to indicate more than one thing.

**Comment by neutrinog** [comment]
ok, so we have a USFM RC type that allows this:

```
my-rc/
   |-gen.usfm
   |-exo.usfm
   ...
```
However what if in the future we decide we want to do the same for osis?

```
my-rc/
   |-gen.osis
   |-exo.osis
   ...
```

It does not make sense to call this a `USFM` RC type because it's in fact osis. So we'd want to make a  new RC type `OSIS` to avoid confusion. However, now we have two duplicate types USFM and OSIS that do exactly the same thing.

I believe the solution would be to have a generic type called `RAW` or `FILE` defined as:

```
my-rc/
   |-FILE1.*
   |-FILE2.*
   ...
```

In this way we can satisfy our need for USFM bundles in addition to potential future needs.

**Comment by neutrinog** [comment]
@jag3773 it's important to point out that when determining what what to do with an RC you'll need to know both of these:

* type
* format

What I'm trying to do is avoid crossing the lines between type and format. Because if we do that then we have an inconsistent spec.

**Comment by neutrinog** [comment]
I have switched the container type to `bundle`. So then a type `bundle` with format `text/usfm` would be a "USFM Bundle".
