### ISSUE TITLE
Support Multiple Projects in a RC

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#13]
* [x] Convert `projects` into a list
* [x] Add a `path` key into each project entry that either specifies a filename in the case of USFM or a directory in the case of other projects

**Comment by neutrinog** [comment]
with regard to USFM above.. we mean USFM container type.

**Comment by neutrinog** [comment]
we might need to make an adjustment to the RC identifiers in RCs that contain multiple projects because we cannot include the project slug since there are multiple.

Perhaps something like this? `en_ulb_book` but then that breaks the order of slugs in the identifier and will be a pain for parsing.

We could instead omit the project slug and leave the delimiters like `en_ulb__book` but that can be  hard to read.

The RC identifier **only** provides a convenience for storing RCs without running into name conflicts. This is not strictly reliable so perhaps we should remove the RC identifier from the spec and let users make things however they want with only a suggested naming convention?

**Comment by neutrinog** [comment]
this is done except for the issues mentioned above.

**Comment by jag3773** [comment]
The slug for a combined ULB would be `en-ulb`, similar for tA, it would be `en-ta`.  What's wrong with that?

**Comment by jag3773** [comment]
This is a non-issue for our API because we are forking the repos into a single Door43-Catalog organization.  Since they are all in the same organization, we can't have duplicate repos.
