### ISSUE TITLE
Use Dublin Core in Manifest

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#16]
Use field names like 'dc.title'.

http://www.dublincore.org/documents/dc-xml-guidelines/
http://dublincore.org/documents/dces/
http://wiki.dublincore.org/index.php/User_Guide

**Comment by neutrinog** [comment]
https://github.com/wilx/dublincore2csl-yaml

**Comment by neutrinog** [comment]
This is done. Just need to make sure any references to the manifest are updated. @jag3773 I looked around a TON and it appears common to leave off the dc prefix when used in yaml. Part of this is due to issues introduced in parsers when you do things like add periods to your keys. I've seem some experiments where they will use semi-colons like `dc;title` but that looked rather ugly. We could do what you originally suggested and prefix with `dc_` however, I might suggest leaving it off because it makes the yaml slightly less readable and there's no standard for parsing DC directly from yaml.
