### ISSUE TITLE
Update package_version to rc_version

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#26]
Change this in manifest.yml and resource catalog (https://github.com/unfoldingWord-dev/door43.org/wiki/API-v3-Resource-Catalog-Endpoint).  Should go in "formats" array where mime_type_version was.

**Comment by neutrinog** [comment]
since we're going to use `.` for #16 let's go ahead and use `.` for rc specific fields as well.

e.g.

* rc.version
* rc.type
* rc.identifier

**Comment by neutrinog** [comment]
This is updated except I have some questions regarding the api.

I'm wondering if we should take the rc.version key out of the resource endpoint entirely and put it in the mime_type like we do for the type and content e.g.

```
"mime_type":"application/zip; rc-type=book rc-content=usfm rc-version=0.2"
```

Because the idea with type and content was that they will not apply to anything but rc's that's true for the rc version as well so we should probably be consistent. So I'd suggest either putting them all in the mime_type or taking them all out.

**Comment by jag3773** [comment]
I don't have a problem with them being in the `mime_type` field, however, I wonder if we are making it more difficult to consume.  If we split them out then we maintain a 1 key = 1 value catalog rather than requiring apps to parse the JSON and then parse the values to get the bit of info they want.

I like keys names like `rc.type`.

**Comment by neutrinog** [comment]
however since the api is serving more than just RCs it would be nice to **not** have rc specific keys all over the place.

Also, we are already doing this for usfm zipballs e.g. `"mime_type": "text/zip; content=usfm"`

**Comment by jag3773** [comment]
Sounds fine.
